# Grammar for model sepcifications.

@@grammar :: ModelSpec

model = outcome:name
        ["|" ~ condition:name ["=" ~ level:integer]]
        "~" predictors:predictors $;

outcome = name;

predictors = "+".{ expression }+;

interaction = interaction:"*".{ name };

SNPs = "SNPs";

name = name:/[A-Za-z0-9_]+/;

# num = num:/-?[0-9]+(\.[0-9]+)?/;
integer = int:/[0-9]+/;

expression =
    | SNPs ~
    | name !"*"
    | interaction
    ;
